---
version: 2.1
orbs:
  cloudsmith: cloudsmith/cloudsmith@1.0.4
jobs:
  build-arm64:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01
    environment:
      - DOCKER_IMAGE=arm64v8/debian:buster
    steps:
      - checkout
      - run: chmod a+x .circleci/*.sh
      - run:
          command: |
            .circleci/build-debian.sh
  publish-deb:
    executor: cloudsmith/default
    steps:
      - cloudsmith/ensure-api-key
      - cloudsmith/install-cli
      - cloudsmith/publish:
          cloudsmith-repository: bbn-projects/bbn-repo
          package-format: debian
          package-distribution: raspbian/buster
          package-path: ../*.deb
workflows:
  version: 2
  build_all:
    jobs:
      - build-arm64
      - publish-deb
