---
version: 2.1
orbs:
  cloudsmith: cloudsmith/cloudsmith@1.0.4
jobs:
  build-buster-arm64:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01
    environment:
      - DOCKER_IMAGE=arm64v8/debian:buster
      - CONTAINER_DISTRO=debian
    steps:
      - checkout
      - run: chmod a+x .circleci/*.sh
      - run:
          command: |
            .circleci/build-debian-armXX.sh
          no_output_timeout: 30m
      - cloudsmith/ensure-api-key
      - cloudsmith/install-cli
      - run: .circleci/publish-cloudsmith.sh deb bbn-projects/bbn-repo raspbian/buster
  build-buster-arm32:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01
    environment:
      - DOCKER_IMAGE=arm32v7/debian:buster
      - CONTAINER_DISTRO=debian
    steps:
      - checkout
      - run: chmod a+x .circleci/*.sh
      - run:
          command: |
            .circleci/build-debian-armXX.sh
          no_output_timeout: 30m
      - cloudsmith/ensure-api-key
      - cloudsmith/install-cli
      - run: .circleci/publish-cloudsmith.sh deb bbn-projects/bbn-repo raspbian/buster
  build-buster:
    docker:
      - image: circleci/buildpack-deps:buster-scm
    environment:
      - CONTAINER_DISTRO=debian
    steps:
      - checkout
      - run: >
          echo "deb-src http://ftp.us.debian.org/debian buster main"
          | sudo tee -a /etc/apt/sources.list
      - run: >
          echo "deb-src http://ftp.us.debian.org/debian buster-updates main"
          | sudo tee -a /etc/apt/sources.list
      - run: cat /etc/apt/sources.list
      - run: chmod a+x .circleci/*.sh
      - run: .circleci/build-debian.sh
      - cloudsmith/ensure-api-key
      - cloudsmith/install-cli
      - run: .circleci/publish-cloudsmith.sh deb bbn-projects/bbn-repo debian/buster
workflows:
  version: 2
  build_all:
    jobs:
      - build-buster-arm64
      - build-buster-arm32
      - build-buster