---
version: 2.1
jobs:
  build-arm64:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01
    environment:
      - DOCKER_IMAGE=arm64v8/debian:buster-20201012
    steps:
      - checkout
      - run: chmod a+x .circleci/*.sh
      - run:
          command: |
            source ".circleci/build-debian.sh"
workflows:
  version: 2
  build_all:
    jobs:
      - build-arm64
