---
version: 2.1
jobs:
  build-arm64:
    docker:
      image: arm64v8/debian:buster-20201012
    steps:
    - checkout
    - run: chmod a+x .circleci/*.sh
    - run:
        command: |
          set
workflows:
  version: 2
  build_all:
    jobs:
      - build-arm64
