---
version: 2.1
jobs:
  build-arm64:
    machine:
      enabled: true
      image: circleci/classic:201808-01
  steps:
    - checkout
    - run: chmod a+x .circleci/*.sh
    - run:
        command: |
          docker run --rm -t arm64v8/debian:buster uname -m
workflows:
  version: 2
  build_all:
    jobs:
      - build-arm64
