---
version: 2.1
orbs:
  cloudsmith: cloudsmith/cloudsmith@1.0.4
jobs:
  build-buster-arm64:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01
    environment:
      - DOCKER_IMAGE=arm64v8/ubuntu:18.04
      - BUILD_ENV=ubuntu
    steps:
      - checkout
      - run: chmod a+x .circleci/*.sh
      - run:
          command: |
            .circleci/build-debian-armXX.sh
            find ~ -name \*.deb
      - cloudsmith/ensure-api-key
      - cloudsmith/install-cli
      - cloudsmith/publish:
          cloudsmith-repository: bbn-projects/bbn-repo
          package-format: deb
          package-distribution: raspbian/buster
          package-path: ../*arm64*.deb
workflows:
  version: 2
  build_all:
    jobs:
      - build-buster-arm64