---
version: 2.1
jobs:
  build-arm64:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01
    environment:
      - DOCKER_IMAGE=arm64v8/debian:buster-20201012
    steps:
      - checkout
      - run: chmod a+x .circleci/*.sh
      - run:
          command: |
            docker run --rm --privileged multiarch/qemu-user-static:x86_64-arm64 --reset
            docker run --rm -t arm64v8/debian:buster-20201012 source ".cirleci/build-debian.sh"
workflows:
  version: 2
  build_all:
    jobs:
      - build-arm64
