---
version: 2.1
orbs:
  cloudsmith: cloudsmith/cloudsmith@1.0.4
jobs:
  build-buster-arm64:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01
    environment:
      - DOCKER_IMAGE=arm64v8/debian:buster
      - CONTAINER_DISTRO=debian
      - EMU=on
    steps:
      - checkout
      - run: chmod a+x .circleci/*.sh
      - run:
          command: |
            .circleci/build-debian.sh
          no_output_timeout: 30m
      - cloudsmith/ensure-api-key
      - cloudsmith/install-cli
      - run: .circleci/publish-cloudsmith.sh deb bbn-projects/bbn-repo raspbian/buster
  build-buster-arm32:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01
    environment:
      - DOCKER_IMAGE=arm32v7/debian:buster
      - CONTAINER_DISTRO=debian
      - EMU=on
    steps:
      - checkout
      - run: chmod a+x .circleci/*.sh
      - run:
          command: |
            .circleci/build-debian.sh
          no_output_timeout: 30m
      - cloudsmith/ensure-api-key
      - cloudsmith/install-cli
      - run: .circleci/publish-cloudsmith.sh deb bbn-projects/bbn-repo raspbian/buster
  build-buster:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01
    environment:
      - CONTAINER_DISTRO=debian
      - DOCKER_IMAGE=circleci/buildpack-deps:buster-scm
      - EMU=off
    steps:
      - checkout
      - run: chmod a+x .circleci/*.sh
      - run:
          command: |
            .circleci/build-debian.sh
          no_output_timeout: 30m
      - cloudsmith/ensure-api-key
      - cloudsmith/install-cli
      - run: .circleci/publish-cloudsmith.sh deb bbn-projects/bbn-repo debian/buster
workflows:
  version: 2
  build_all:
    jobs:
      - build-buster-arm64
      - build-buster-arm32
      - build-buster