---
version: 2.1
jobs:
  build-arm64:
    machine: true
    environment:
      - DOCKER_IMAGE=arm64v8/debian:buster-20201012
    steps:
    - checkout
    - setup_remote_docker:
        version: 19.03.13
     - run: chmod a+x .circleci/*.sh
    - run:
        command:
          set
workflows:
  version: 2
  build_all:
    jobs:
      - build-arm64
