---
version: 2.1
jobs:
  build-arm64:
    machine:
      enabled: true
    environment:
    steps:
      - checkout
      - run: chmod a+x .circleci/*.sh
      - run:
          command: |
            source ".circleci/parse-tag.sh"
workflows:
  version: 2
  build_all:
    jobs:
      - build-arm64
