---
version: 2.1
orbs:
  cloudsmith: cloudsmith/cloudsmith@1.0.4
commands:
  publish-buster-deb:
    steps:
      - cloudsmith/ensure-api-key
      - cloudsmith/install-cli
      - run: echo `find ~ -name \*.deb`
      - cloudsmith/publish:
          cloudsmith-repository: bbn-projects/bbn-repo
          package-format: debian
          package-distribution: raspbian/buster
          package-path: ./*.deb
jobs:
  build-buster-arm64:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01
    environment:
      - DOCKER_IMAGE=arm64v8/debian:buster
    steps:
      - checkout
      - run: chmod a+x .circleci/*.sh
      - run:
          command: |
            .circleci/build-debian.sh
      - run: publish-buster-deb
  build-buster-arm32:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01
    environment:
      - DOCKER_IMAGE=arm32v8/debian:buster
    steps:
      - checkout
      - run: chmod a+x .circleci/*.sh
      - run:
          command: |
            .circleci/build-debian.sh
      - run: publish-buster-deb
workflows:
  version: 2
  build_all:
    jobs:
      - build-buster-arm64
      - build-buster-arm32
